# Generated by Django 2.2 on 2019-04-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(blank=True, default='in months', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='institute_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='upload_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='users/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='validity_of_certification',
            field=models.CharField(blank=True, default='in years', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, choices=[('10', '10'), ('12', '12'), ('diploma', 'DIPLOMA'), ('under graduation', 'UNDER GRADUATION'), ('post graduation', 'POST GRADUATION')], default='10', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.CharField(blank=True, default='in years', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='pencentile',
            field=models.CharField(blank=True, default='in numbers', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='roll_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='upload_marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='users/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_passing',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='other_doc',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='other_doc',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='other_doc',
            name='document_3',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Document 3'),
        ),
        migrations.AlterField(
            model_name='other_doc',
            name='document_4',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Document 4'),
        ),
        migrations.AlterField(
            model_name='other_doc',
            name='document_5',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Document 5'),
        ),
        migrations.AlterField(
            model_name='other_doc',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Signature Photo'),
        ),
        migrations.AlterField(
            model_name='other_doc',
            name='signed_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Singed Photo'),
        ),
        migrations.AlterField(
            model_name='other_doc',
            name='thumb_impression_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Thumb Impression Photo'),
        ),
    ]
