# Generated by Django 2.2 on 2019-05-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20190524_0225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QRCode',
            new_name='ProfileQRCode',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
